# Generated by Django 3.2.19 on 2023-05-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Continents',
            fields=[
                ('continent_id', models.AutoField(primary_key=True, serialize=False)),
                ('continent_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('event_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('fixture_id', models.AutoField(primary_key=True, serialize=False)),
                ('match_day', models.SmallIntegerField(default=0)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Leagues',
            fields=[
                ('league_id', models.AutoField(primary_key=True, serialize=False)),
                ('league_name', models.CharField(max_length=50)),
                ('total_teams', models.SmallIntegerField(default=0)),
                ('match_day', models.SmallIntegerField(default=0)),
                ('is_concluded', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('manager_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('career_start', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('attendance', models.IntegerField(default=0)),
                ('result', models.BooleanField(default=False)),
                ('extra_time', models.BooleanField(default=False)),
                ('injury_time', models.SmallIntegerField(default=0)),
                ('home_team_goals', models.SmallIntegerField(default=0)),
                ('away_team_goals', models.SmallIntegerField(default=0)),
                ('home_team_possession', models.SmallIntegerField(default=0)),
                ('away_team_possession', models.SmallIntegerField(default=0)),
                ('home_team_shots', models.SmallIntegerField(default=0)),
                ('away_team_shots', models.SmallIntegerField(default=0)),
                ('home_team_shots_on_target', models.SmallIntegerField(default=0)),
                ('away_team_shots_on_target', models.SmallIntegerField(default=0)),
                ('home_team_shots_off_target', models.SmallIntegerField(default=0)),
                ('away_team_shots_off_target', models.SmallIntegerField(default=0)),
                ('home_team_shots_blocked', models.SmallIntegerField(default=0)),
                ('away_team_shots_blocked', models.SmallIntegerField(default=0)),
                ('home_team_corner_kicks', models.SmallIntegerField(default=0)),
                ('away_team_corner_kicks', models.SmallIntegerField(default=0)),
                ('home_team_offsides', models.SmallIntegerField(default=0)),
                ('away_team_offsides', models.SmallIntegerField(default=0)),
                ('home_team_fouls', models.SmallIntegerField(default=0)),
                ('away_team_fouls', models.SmallIntegerField(default=0)),
                ('home_team_throw_ins', models.SmallIntegerField(default=0)),
                ('away_team_throw_ins', models.SmallIntegerField(default=0)),
                ('home_team_yellow_cards', models.SmallIntegerField(default=0)),
                ('away_team_yellow_cards', models.SmallIntegerField(default=0)),
                ('home_team_red_cards', models.SmallIntegerField(default=0)),
                ('away_team_red_cards', models.SmallIntegerField(default=0)),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fixtures')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leagues')),
            ],
        ),
        migrations.CreateModel(
            name='Nations',
            fields=[
                ('nation_id', models.AutoField(primary_key=True, serialize=False)),
                ('nation_name', models.CharField(max_length=50)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.continents')),
            ],
        ),
        migrations.CreateModel(
            name='PitchLocations',
            fields=[
                ('pitch_area_id', models.AutoField(primary_key=True, serialize=False)),
                ('pitch_area_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRoles',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season_name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_concluded', models.BooleanField(default=False)),
                ('number_of_leagues', models.SmallIntegerField(default=0)),
                ('number_of_matches', models.IntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('avg_goals_per_match', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('stadium_id', models.AutoField(primary_key=True, serialize=False)),
                ('stadium_name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cities')),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nations')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=50)),
                ('est_date', models.DateField(null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leagues')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.managers')),
                ('stadium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stadiums')),
            ],
        ),
        migrations.CreateModel(
            name='Referees',
            fields=[
                ('referee_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('career_start', models.DateField()),
                ('matches_officiated', models.SmallIntegerField(default=0)),
                ('yellow_cards_issued', models.IntegerField(default=0)),
                ('red_cards_issued', models.IntegerField(default=0)),
                ('penalty_decisions_overturned', models.IntegerField(default=0)),
                ('other_decisions_overturned', models.IntegerField(default=0)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nations')),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('height', models.FloatField(default=0)),
                ('weight', models.FloatField(default=0)),
                ('total_appearances', models.IntegerField(default=0)),
                ('nation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nations')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playerroles')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teams')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvents',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('minute', models.SmallIntegerField(default=0)),
                ('second', models.SmallIntegerField(default=0)),
                ('is_extra_time', models.BooleanField(default=False)),
                ('associated_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_player', to='core.players')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.eventtypes')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.matches')),
                ('pitch_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pitchlocations')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player', to='core.players')),
            ],
        ),
        migrations.AddField(
            model_name='matches',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.referees'),
        ),
        migrations.AddField(
            model_name='matches',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seasons'),
        ),
        migrations.AddField(
            model_name='matches',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stadiums'),
        ),
        migrations.AddField(
            model_name='matches',
            name='winner_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.teams'),
        ),
        migrations.AddField(
            model_name='managers',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nations'),
        ),
        migrations.CreateModel(
            name='LeagueTables',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('points', models.SmallIntegerField(default=0)),
                ('position', models.SmallIntegerField(blank=True)),
                ('matches_played', models.SmallIntegerField(default=0)),
                ('matches_won', models.SmallIntegerField(default=0)),
                ('matches_drawn', models.SmallIntegerField(default=0)),
                ('maches_lost', models.SmallIntegerField(default=0)),
                ('goals_scored', models.IntegerField(default=0)),
                ('goals_against', models.IntegerField(default=0)),
                ('goal_difference', models.SmallIntegerField(default=0)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leagues')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seasons')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teams')),
            ],
        ),
        migrations.AddField(
            model_name='leagues',
            name='champion_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champion_team', to='core.teams'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='most_assists',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_assists', to='core.players'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nations'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='runner_up_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runner_up_team', to='core.teams'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seasons'),
        ),
        migrations.AddField(
            model_name='leagues',
            name='top_scorer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_scorer', to='core.players'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='core.teams'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='away_team_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_manager', to='core.managers'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='core.teams'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='home_team_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_manager', to='core.managers'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.leagues'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='referee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.referees'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seasons'),
        ),
        migrations.AddField(
            model_name='fixtures',
            name='stadium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stadiums'),
        ),
        migrations.AddField(
            model_name='cities',
            name='nation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.nations'),
        ),
    ]
