# Generated by Django 3.2.19 on 2023-05-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20230508_2339'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cities',
            new_name='City',
        ),
        migrations.RenameModel(
            old_name='Continents',
            new_name='Continent',
        ),
        migrations.RenameModel(
            old_name='EventTypes',
            new_name='EventType',
        ),
        migrations.RenameModel(
            old_name='Fixtures',
            new_name='Fixture',
        ),
        migrations.RenameModel(
            old_name='Leagues',
            new_name='League',
        ),
        migrations.RenameModel(
            old_name='LeagueTables',
            new_name='LeagueTable',
        ),
        migrations.RenameModel(
            old_name='Managers',
            new_name='Manager',
        ),
        migrations.RenameModel(
            old_name='Matches',
            new_name='Match',
        ),
        migrations.RenameModel(
            old_name='MatchEvents',
            new_name='MatchEvent',
        ),
        migrations.RenameModel(
            old_name='Nations',
            new_name='Nation',
        ),
        migrations.RenameModel(
            old_name='PitchLocations',
            new_name='PitchLocation',
        ),
        migrations.RenameModel(
            old_name='Players',
            new_name='Player',
        ),
        migrations.RenameModel(
            old_name='PlayerRoles',
            new_name='PlayerRole',
        ),
        migrations.RenameModel(
            old_name='Referees',
            new_name='Referee',
        ),
        migrations.RenameModel(
            old_name='Seasons',
            new_name='Season',
        ),
        migrations.RenameModel(
            old_name='Stadiums',
            new_name='Stadium',
        ),
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
