# Generated by Django 3.2.19 on 2023-05-08 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230509_0141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='dob',
            new_name='date_of_birth',
        ),
    ]
