# Generated by Django 3.2.19 on 2023-05-08 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230509_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_of_team', to='core.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_manager', to='core.manager'),
        ),
    ]
