# Generated by Django 3.2.19 on 2023-05-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230509_0329'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersy_number',
            field=models.SmallIntegerField(default=0, null=True),
        ),
    ]
