# Generated by Django 3.2.19 on 2023-05-08 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_league_top_scorer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='champion_team',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='champion_team', to='core.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='most_assists',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='most_assists', to='core.player'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='runner_up_team',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='runner_up_team', to='core.team'),
            preserve_default=False,
        ),
    ]
