# Generated by Django 3.2.19 on 2023-05-08 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20230509_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_of_team', to='core.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='jersy_number',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='team',
            name='est_date',
            field=models.DateField(default='1900-01-01'),
            preserve_default=False,
        ),
    ]
