# Generated by Django 3.2.19 on 2023-05-09 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20230509_0458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='champion_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champion_team', to='core.team'),
        ),
    ]
