# Generated by Django 3.2.19 on 2023-05-09 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_league_champion_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='most_assists',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_assists', to='core.player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='runner_up_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runner_up_team', to='core.team'),
        ),
        migrations.AlterField(
            model_name='league',
            name='top_scorer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_scorer', to='core.player'),
        ),
    ]
