# Generated by Django 3.2.19 on 2023-05-09 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230510_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchStatus',
            fields=[
                ('match_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='fixture',
            name='status',
        ),
        migrations.AddField(
            model_name='fixture',
            name='match_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.matchstatus'),
            preserve_default=False,
        ),
    ]
