# Generated by Django 3.2.19 on 2023-05-09 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230510_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='date',
        ),
        migrations.RemoveField(
            model_name='match',
            name='league',
        ),
        migrations.RemoveField(
            model_name='match',
            name='referee',
        ),
        migrations.RemoveField(
            model_name='match',
            name='season',
        ),
        migrations.RemoveField(
            model_name='match',
            name='stadium',
        ),
        migrations.RemoveField(
            model_name='match',
            name='time',
        ),
    ]
