# Generated by Django 3.2.19 on 2023-05-10 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20230510_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_players',
            field=models.TextField(blank=True, null=True, verbose_name='Favorite Players'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_team',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Favorite Team'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Username'),
        ),
    ]
