# Generated by Django 3.2.19 on 2023-05-10 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20230510_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='team',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_of_team', to='core.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_manager', to='core.manager'),
        ),
    ]
