# Generated by Django 3.2.19 on 2023-05-10 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20230510_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stadium',
            name='nation',
        ),
    ]
