# Generated by Django 3.2.19 on 2023-05-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_player_career_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaguetable',
            name='position',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
