# Generated by Django 3.2.19 on 2023-05-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_leaguetable_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='away_team_manager',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='home_team_manager',
            field=models.CharField(max_length=50),
        ),
    ]
