# Generated by Django 3.2.19 on 2023-05-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20230511_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='first_name',
            new_name='manager_name',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='first_name',
            new_name='player_name',
        ),
        migrations.RenameField(
            model_name='referee',
            old_name='first_name',
            new_name='referee_name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='referee',
            name='last_name',
        ),
    ]
