# Generated by Django 3.2.19 on 2023-05-14 13:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Favorite Players'), default=None, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_team',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Favorite Teams'), size=None),
        ),
    ]
