# Generated by Django 3.2.19 on 2023-05-14 13:47

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_auto_20230514_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='champion_team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='champion_team', to='core.team'),
        ),
        migrations.AlterField(
            model_name='league',
            name='most_assists',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='most_assists', to='core.player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='runner_up_team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='runner_up_team', to='core.team'),
        ),
        migrations.AlterField(
            model_name='league',
            name='top_scorer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_scorer', to='core.player'),
        ),
        migrations.AlterField(
            model_name='leaguetable',
            name='position',
            field=models.SmallIntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='team',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_of_team', to='core.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner_team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='associated_player',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associated_player', to='core.player'),
        ),
        migrations.AlterField(
            model_name='matchevent',
            name='pitch_area',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pitchlocation'),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersy_number',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_manager', to='core.manager'),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nation'),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Favorite Players'), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorite_team',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50, verbose_name='Favorite Teams'), blank=True, default=None, null=True, size=None),
        ),
    ]
