# Generated by Django 3.2.19 on 2023-05-18 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20230514_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerrole',
            name='role_key',
            field=models.CharField(default='GK', max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
