# Generated by Django 3.2.19 on 2023-05-20 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_playerrole_role_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='champion_team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='champion_team', to='core.team'),
        ),
        migrations.AlterField(
            model_name='league',
            name='most_assists',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='most_assists', to='core.player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='runner_up_team',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_up_team', to='core.team'),
        ),
        migrations.AlterField(
            model_name='league',
            name='top_scorer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_scorer', to='core.player'),
        ),
    ]
