# Generated by Django 3.2.19 on 2023-05-21 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_team_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player', to='core.player'),
        ),
    ]
