# Generated by Django 3.2.19 on 2023-05-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_matchevent_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leaguetable',
            old_name='maches_lost',
            new_name='matches_lost',
        ),
    ]
