# Generated by Django 3.2.19 on 2023-05-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_rename_maches_lost_leaguetable_matches_lost'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='motm',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.player'),
        ),
    ]
