# Generated by Django 3.2.19 on 2023-05-29 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_fixture_motm'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='top_scorer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.player'),
        ),
    ]
